import "./globals.css";

export const metadata = {
  title: "password generator",
  description: "password generator Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
